name: CISC 3140 Fall 2022 Lab 2

on:
  push:
      branches: [ "main" ]
      
jobs:
    JavaProg:
        
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v3
        - run: echo "Compiling and executing Lab2 java program"
        - name: create java program and use file redirection
        - run: javac ./lab2/Lab2DueDates.java
        - run: java -cp ./classes;. Lab2DueDates < ./lab2/lab2data.txt
          
    ZShellScript:

        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v3
        - run: echo "Running ZSH file"
        - name: run java and zsh programs
          run: cd ./lab2 && ./sample.sh
          
    MakeJavaProg:
    
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v3
        - run: echo "Running makefile"
        - name: run programs by makefile
          run: cd ./lab2 && make lab2
