name: CISC 3140 Fall 2022 Lab 2

on:
  push:
      branches: [ "main" ]
      
jobs:
    JavaProg:
        
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v3
        - run: cd lab2
        - name: compile and execute java program
          run: javac -cp Lab2DueDates.class Lab2DueDates.java
        - run: java Lab2DueDates < lab2data.txt
          
    ZShellScript:
    
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v3
        - name: run java and zsh programs
          run: cd lab2 && ./sample.sh
          
    MakeJavaProg:
    
        runs-on: macos-latest
        
        steps:
        - uses: actions/checkout@v3
        - name: run programs by makefile
          run: cd lab2 && make lab2
